Kaartje2go/Dullahan

packages/dullahan-adapter-puppeteer/src/DullahanAdapterPuppeteer.ts, packages/dullahan-adapter-puppeteer/src/DullahanAdapterPuppeteerOptions.ts
This adds the option to provide a `userAgent` to the `dullahan-puppeteer-plugin`. It will be appended to the actual `user agent`.
=> chore: add the option to append a custom user agent in puppeteer

packages/dullahan-plugin-github/package.json, packages/dullahan-plugin-github/src/DullahanPluginGithub.ts, packages/dullahan-runner-aws-lambda/src/DullahanRunnerAwsLambda.ts, yarn.lock
This upgrades the `octokit` dependency and renames `createStatus` to `createCommitStatus`.
This adds some logging to the AWS lambda runner.
=> chore: upgrade octokit and fix commit status warning

__snapshots__/env_nodejs/exports.ts.snap, packages/dullahan-runner-aws-lambda/src/DullahanRunnerAwsLambda.ts, packages/dullahan-runner-aws-lambda/src/DullahanRunnerAwsLambdaOptions.ts
This updates the testdata to not be a string, but an object that has a success and failures property. This was implemented incorrectly.
This adds the useAccessKeys property, so we can call lambda functions from within a lambda function
=> chore: update testdata in lambda runner and add useAccessKeys property

packages/dullahan-adapter-puppeteer/src/DullahanAdapterPuppeteer.ts, packages/dullahan-adapter-puppeteer/src/DullahanAdapterPuppeteerOptions.ts
This allows using a custom binary as a browser.
=> chore: allow passing executablePath to puppeteer

__snapshots__/env_nodejs/exports.ts.snap, packages/dullahan-adapter-puppeteer/src/DullahanAdapterPuppeteer.ts, packages/dullahan-adapter-puppeteer/src/DullahanAdapterPuppeteerOptions.ts
This adds several missing options to the puppeteer adapter, so it can run in a Lambda environment
=> chore: add options to puppeteer adapter

packages/dullahan-runner-aws-lambda/src/DullahanRunnerAwsLambda.ts, packages/dullahan/src/DullahanClient.ts
This removes some unneeded code (emitting is already done in another part of the code).
This also makes sure the function will return, even if there are no `calls`.
=> chore: remove unneeded code

packages/dullahan-adapter-puppeteer/src/DullahanAdapterPuppeteer.ts
If there is a protocol error, we should retry the function. This is because navigation can take some time, and the command will fail because navigation is in progress.
=> chore: handle protocol error

__tests__/env_browser/adapter/scrollToElement.ts, packages/dullahan-adapter-playwright/src/DullahanAdapterPlaywright.ts, packages/dullahan-adapter-puppeteer/src/DullahanAdapterPuppeteer.ts, packages/dullahan-adapter-selenium-3/src/DullahanAdapterSelenium3.ts, packages/dullahan-adapter-selenium-4/src/DullahanAdapterSelenium4.ts, packages/dullahan/src/adapter/DullahanAdapter.ts, packages/dullahan/src/browser_helpers/findElement.ts
This implements an interactiveOnly option when finding elements. It prevents the visibility check from failing, since an element does not need to be interactive to be visible.
=> chore: create separate interactiveonly findOption

packages/dullahan-adapter-playwright/src/DullahanAdapterPlaywright.ts, packages/dullahan-adapter-puppeteer/src/DullahanAdapterPuppeteer.ts, packages/dullahan-adapter-selenium-3/src/DullahanAdapterSelenium3.ts, packages/dullahan-adapter-selenium-4/src/DullahanAdapterSelenium4.ts, packages/dullahan/src/adapter/DullahanAdapter.ts, packages/dullahan/src/browser_helpers/setElementProperty.ts
This implements the waitForElementInteractive command.
This fixes an issue where using a Select element does not trigger Events in the DOM.
=> chore: implement waitforelementinteractive command

packages/dullahan-plugin-aws-s3/src/DullahanPluginAwsS3.ts, packages/dullahan-plugin-github/src/DullahanPluginGithub.ts, packages/dullahan-plugin-report-markdown/src/DullahanPluginReportMarkdown.ts, packages/dullahan-plugin-report-markdown/src/helpers/formatter.ts
- Hide only the body of the table of successful/slow/unstable tests and show a line even if there are 0 of these tests.
- Do not replace possible secrets inside a base64 (this triggers a promise rejection)
=> chore: improve markdown and do not replace in base64

packages/dullahan-adapter-playwright/src/DullahanAdapterPlaywright.ts, packages/dullahan-adapter-puppeteer/src/DullahanAdapterPuppeteer.ts, packages/dullahan-adapter-selenium-3/src/DullahanAdapterSelenium3.ts, packages/dullahan-adapter-selenium-4/src/DullahanAdapterSelenium4.ts, packages/dullahan/src/adapter/DullahanAdapter.ts
This implements an executeScript function, which allows for custom functions to be run in the browser.
=> chore: implement an executescript function

packages/dullahan-adapter-puppeteer/src/DullahanAdapterPuppeteer.ts, packages/dullahan-plugin-github/src/DullahanPluginGithub.ts
This makes sure clicks are performed when the element is visible.
This also lowers the time before updating the github status.
=> chore: do not check for interactive when clicking

packages/dullahan-adapter-playwright/src/DullahanAdapterPlaywright.ts, packages/dullahan-adapter-puppeteer/src/DullahanAdapterPuppeteer.ts, packages/dullahan-adapter-selenium-3/src/DullahanAdapterSelenium3.ts, packages/dullahan-adapter-selenium-4/src/DullahanAdapterSelenium4.ts, packages/dullahan/src/adapter/DullahanAdapter.ts, packages/dullahan/src/api/DullahanApi.ts
This makes `click()` use the default adapter `click()`, instead of always using offsets.
=> chore: add simple click method

packages/dullahan-runner-aws-lambda/src/DullahanRunnerAwsLambdaOptions.ts
Allow passing custom http options to the lambda runner
=> chore: add http options to the lambda runner

packages/dullahan-plugin-github/src/DullahanPluginGithub.ts
Github comment now shows the html report link, if a link is available.
=> chore: add html report link to github plugin output

packages/dullahan-plugin-report-html/template/partials/test.ejs, packages/dullahan-runner-aws-lambda/src/DullahanRunnerAwsLambda.ts
- Show the test time in the default html report template.
- Log the payload when the lambda runner fails on parsing it
=> chore: show test time in html report

__snapshots__/env_nodejs/exports.ts.snap, packages/dullahan-plugin-report-markdown/src/DullahanPluginReportMarkdownOptions.ts, packages/dullahan/src/DullahanClient.ts
- Make sure the `StoredArtifacts` are evaluated after the promises are resolved.
- Set the `slowTestThreshold` in the markdown report to 60 seconds, just like in other plugins.
=> chore: improve markdown report

packages/dullahan-plugin-report-html/template/partials/test.ejs, packages/dullahan-plugin-report-markdown/src/DullahanPluginReportMarkdown.ts, packages/dullahan-plugin-report-markdown/src/helpers/formatter.ts, packages/dullahan-runner-aws-lambda/src/DullahanRunnerAwsLambda.ts, packages/dullahan/src/DullahanClient.ts
- Add `await`s to make sure the promises are actually resolved
- Fix a typo in html report
- Do not emit unneeded `testStart`
=> fix: make sure artifacts are parsed correctly

packages/dullahan/package.json, packages/dullahan/src/DullahanClient.ts, yarn.lock
Plugins can no longer modify DullahanTestEndCall and
DullahanFunctionEndCall data.
=> fix: Plugins can no longer modify data

packages/dullahan/src/api/DullahanApi.ts
We are now able to set the return type of executeScript.
=> chore: Added better typings for executeScript method

packages/dullahan-plugin-slack/src/DullahanPluginSlack.ts, packages/dullahan-plugin-slack/src/DullahanPluginSlackOptions.ts
Use the mention option in the slack plugin if there are failing tests
=> fix: use the mention option if there are failing tests

packages/dullahan-adapter-puppeteer/src/DullahanAdapterPuppeteer.ts
The Lambda runner was exceeding the maximum allowed payload size - this should fix it. In the future, we should make this configurable in the puppeteer options.
=> fix: do not screenshot full page to decrease size

packages/dullahan-adapter-selenium-3/src/DullahanAdapterSelenium3.ts
Change the timeout from `1` to `15000`, because it would always fail otherwise.
=> fix: use default timeout of 15000

packages/dullahan-adapter-selenium-4/package.json, yarn.lock
Downgraded selenium webdriver to 4.0.0-alpha.6 which is the highest
version currently supported on browserstack.
=> chore: downgrade selenium webdriver

packages/dullahan-plugin-slack/src/DullahanPluginSlack.ts
As stated in PR title - this only prints the value of mention if it is defined.
=> fix: only mention if the value is defined

packages/dullahan-adapter-selenium-4/src/DullahanAdapterSelenium4.ts
Selenium/Appium threw an error when fractal numbers where passed to the
mouse move action. This could cause methods like clickAtElement to fail.
=> fix: Fixed problem with mouse coordinates not being integer

packages/dullahan-adapter-selenium-4/src/DullahanAdapterSelenium4.ts, packages/dullahan-adapter-selenium-4/src/DullahanAdapterSelenium4Options.ts
The selenium 4 adapter can now use events instead of actions for
browsers that don't support actions. A new option was added `useActions`
which default is set too true, set it too `false` to use events.
BREAKING CHANGE: 🧨 The selenium 4 adapter no longer automatically uses some events instead of
actions on edge, you need to manually set the `useActions` option too `false`.
=> feat: Selenium 4 can now use events instead of actions.

packages/dullahan-adapter-puppeteer/src/DullahanAdapterPuppeteer.ts, packages/dullahan-adapter-puppeteer/src/DullahanAdapterPuppeteerOptions.ts
Puppeteer can now be configured to use touch instead of clicks, by
setting the `useTouch` option.
=> feat: Puppeteer can now use touch instead of click.

packages/dullahan-plugin-github/src/DullahanPluginGithub.ts, packages/dullahan/src/DullahanClient.ts, packages/dullahan/src/DullahanPlugin.ts
Use a flag in `dullahan.stop()` so we can terminate early and set the github status to a failure. We can use this in the future to improve other plugins as well.
=> feat: use earlytermination flag to set failure state

.github/workflows/nodejs.yml, packages/dullahan-plugin-report-html/src/DullahanPluginReportHtml.ts, packages/dullahan-plugin-report-html/template/partials/config.ejs, packages/dullahan-plugin-report-html/template/partials/styles.ejs, packages/dullahan-plugin-report-html/template/report.ejs, packages/dullahan/src/DullahanClient.ts
Improve the html report by showing the used dullahan configuration. This will make debugging easier.
=> chore: show dullahan configuration in the html report

packages/dullahan-adapter-selenium-4/package.json, packages/dullahan-adapter-selenium-4/src/browsers/AppleSafari.ts, packages/dullahan-adapter-selenium-4/src/browsers/GoogleChrome.ts, packages/dullahan-adapter-selenium-4/src/browsers/MicrosoftEdge.ts, packages/dullahan-adapter-selenium-4/src/browsers/MicrosoftInternetExplorer.ts, packages/dullahan-adapter-selenium-4/src/browsers/MozillaFirefox.ts, packages/dullahan-adapter-selenium-4/src/browsers/Unknown.ts
rawCapabilities in configs where completelty overwriting the default
capabilities when using selenium 4, this fix makes sure the capabilities
are properly deep merged
=> fix: rawCapabilities no longer override

packages/dullahan/src/api/DullahanApi.ts
Use waitForElementInteractive instead of visible inside 'click()'. This will make sure if the given element is not clickable(e.g. interactive) it will autoscroll(when enabled).
=> Fix autoscroll for click

packages/dullahan-adapter-puppeteer/src/DullahanAdapterPuppeteer.ts
https://dullahan-artifacts.s3.eu-central-1.amazonaws.com/artifacts/dullahan-plugin-report-html/report-1614901701824.html
```
2021-03-04T23:42:32.454Z	07bfc15e-6103-4590-baff-54124f1afbd5	INFO	api click [ '.swal2-cancel' ]
2021-03-04T23:42:32.454Z 07bfc15e-6103-4590-baff-54124f1afbd5 INFO api click [ '.swal2-cancel' ]
2021-03-04T23:42:32.454Z	07bfc15e-6103-4590-baff-54124f1afbd5	INFO	adapter isElementInteractable [ '.swal2-cancel' ]
2021-03-04T23:42:32.454Z 07bfc15e-6103-4590-baff-54124f1afbd5 INFO adapter isElementInteractable [ '.swal2-cancel' ]
2021-03-05T00:42:32.507+01:00	2021-03-04T23:42:32.507Z 07bfc15e-6103-4590-baff-54124f1afbd5 INFO adapter waitForElementInteractive [ '.swal2-cancel', { timeout: 15000 } ]
2021-03-04T23:42:32.559Z	07bfc15e-6103-4590-baff-54124f1afbd5	INFO	adapter …
```
=> throw error on timeout so thate we are not stuck in infinite recursive loop

.github/workflows/release.yml, packages/dullahan-adapter-puppeteer/src/DullahanAdapterPuppeteer.ts
clicks can also break because of native dialogs
=> Also disable dialogs for clicks

__snapshots__/env_nodejs/exports.ts.snap, packages/dullahan/__tests__/dependencies.ts, packages/dullahan/src/nodejs_helpers/index.ts, packages/dullahan/src/nodejs_helpers/requireDependency.ts, packages/dullahan/src/nodejs_helpers/types.ts
Dependency resolution contained a lot of guessing during runtime;
this change reduces the amount of guessing.
BREAKING CHANGE: Config files that have relative paths like
'MyDullahanApi.ts' must be updated to './MyDullahanApi.ts' to be
resolved relative to the current working directory.
=> chore: simplify dependency resolution

packages/dullahan-runner-aws-lambda/src/DullahanRunnerAwsLambda.ts, packages/dullahan/src/runner/DullahanRunnerOptions.ts
This also allows us to remove a Kaartje2go-specific configuration
where the runner would always quit after 20 tests have failed,
regardless of the provided options
=> feat: accept a number of failures for the failFast option

__snapshots__/env_nodejs/exports.ts.snap, packages/dullahan-runner-aws-lambda/src/DullahanRunnerAwsLambda.ts, packages/dullahan-runner-aws-lambda/src/DullahanRunnerAwsLambdaOptions.ts
This allows us to remove a Kaartje2go-specific configuration
where the runner would throttle the starting of slaves with
a static rate-limiter; it is now an option with a value X
meaning "Start X slaves per second, up to the maximum concurrency."
=> feat: add rateLimitConcurrency option

__snapshots__/env_nodejs/exports.ts.snap, packages/dullahan-runner-aws-lambda/src/DullahanRunnerAwsLambda.ts, packages/dullahan-runner-aws-lambda/src/DullahanRunnerAwsLambdaOptions.ts, packages/dullahan-runner-development/src/DullahanRunnerDevelopment.ts, packages/dullahan/__tests__/ensureScopedOptions.ts, packages/dullahan/src/DullahanClient.ts, packages/dullahan/src/DullahanConfig.ts, packages/dullahan/src/adapter/DullahanAdapter.ts, packages/dullahan/src/api/DullahanApi.ts, packages/dullahan/src/nodejs_helpers/artifacts.ts, packages/dullahan/src/nodejs_helpers/options.ts, packages/dullahan/src/nodejs_helpers/types.ts, packages/dullahan/src/runner/DullahanRunner.ts
On AWS Lambda, building and deploying your Dullahan functions can be
quite tricky depending on your setup. Allowing files to be passed as
constructors or instances allows tools like webpack to bundle everything
into one convenient file for you to deploy on AWS Lambda.
=> feat: allow tests to be passed as instances

packages/dullahan-plugin-report-html/src/DullahanPluginReportHtml.ts, packages/dullahan-plugin-report-html/src/DullahanPluginReportHtmlOptions.ts
This change allows compiled versions of the plugins to work with
an inlined version as option. It's not perfect, but it's a good step in
the right direction.
=> feat: add support for inlined templates

packages/dullahan/src/DullahanClient.ts, packages/dullahan/src/DullahanTest.ts
The previous solution didn't exactly work as expected,
as the source for the hash was always [object Object]
and thus resulted in all tests having the same id if
provided through instances
=> fix: generate test ids based on test content

packages/dullahan-adapter-playwright/src/DullahanAdapterPlaywright.ts, packages/dullahan-adapter-puppeteer/src/DullahanAdapterPuppeteer.ts, packages/dullahan-adapter-selenium-3/src/DullahanAdapterSelenium3.ts, packages/dullahan-adapter-selenium-4/src/DullahanAdapterSelenium4.ts, packages/dullahan-runner-development/src/DullahanRunnerDevelopment.ts, packages/dullahan/src/adapter/DullahanAdapter.ts, packages/dullahan/src/api/DullahanApi.ts
BREAKING CHANGE: For puppeteer, you will now
have to disable dialogs in your tests yourself.
=> feat: add dialog handling functionality

packages/dullahan-runner-aws-lambda/src/DullahanRunnerAwsLambda.ts, scripts/ci/jobs/test_playwright_webkit.sh
Sometimes, it seems the JSON does not need double parsing - this prevents a SyntaxError and also cleans up the code a bit.
=> fix: improve json parsing in lambda runner

package.json, packages/dullahan-adapter-puppeteer/package.json, packages/dullahan-adapter-puppeteer/src/DullahanAdapterPuppeteer.ts, packages/dullahan-adapter-selenium-4/src/DullahanAdapterSelenium4.ts, yarn.lock
custom goto logic is more prone to errors. Should try provided defaults instead.
For puppeteer there is goto for example
For selenium(4) there is [.get](https://www.selenium.dev/documentation/webdriver/browser/navigation/#navigate-to)
By default load strategy is to wait for window to be completed but you can update strategy via [capabilities](https://www.selenium.dev/documentation/webdriver/capabilities/shared/#pageloadstrategy)
=> improve goto

packages/dullahan/src/DullahanCall.ts
Don't truncate the result of openBrowser because it's used to set the test name and status in Browserstack
=> fix: browserstack-testname-and-status

packages/dullahan-plugin-browserstack/src/DullahanPluginBrowserstack.ts
**Fix:**
Remove `/sessions` from the session browser_url to create a correct build url
**Description:**
The `browser_url` looked for example like this with the format `/builds/{build_id}/sessions/{hashed_id}`: https://automate.browserstack.com/builds/fb0e9da85f3d6ef2a43f3d93fd1f1171d015a4da/sessions/8e2f2cb124669676183d0efa52ec331ab6b34b8c
To create the build url we removed the `/{hashed_id}`, but the `/sessions` should also be removed 
So previously it looked like `/builds/{build_id}/sessions`
Now it will look like `/builds/{build_id}`
**What is it for?:**
To fix this browserstack link in our Slack alert channel
=> fix: correct browserstackBuildUrl for Slack link

packages/dullahan-adapter-selenium-4/package.json, yarn.lock
Reverts Kaartje2go/Dullahan#292
This seems to break runs on browserstack due to required authorization.
=> Revert "fix(deps): update dependency selenium-webdriver to v4.5.0"

packages/dullahan-plugin-report-html/template/partials/styles.ejs
This page is really big and heavy
https://web.dev/content-visibility/
=> Improve initial load time by skipping the rendering of offscreen content

packages/dullahan-adapter-playwright/src/DullahanAdapterPlaywright.ts, packages/dullahan-adapter-puppeteer/src/DullahanAdapterPuppeteer.ts, packages/dullahan-adapter-selenium-4/src/DullahanAdapterSelenium4.ts, packages/dullahan/src/adapter/DullahanAdapter.ts, packages/dullahan/src/browser_helpers/emitFakeEvent.ts
Implement context click / right mouse button click.
This doesn't seem to be an option for Selenium 3, it also doesn't work in puppeteer with `useTouch`.
=> feat: implement context click
