- scripts/yarn/ensure_packagejson.ts
Build process obviously doesn't like it very much
> fix: stop resetting versions to 0.0.0

- packages/dullahan-plugin-aws-s3/src/DullahanPluginAwsS3.ts
It is possible that `/regex/.exec()` returns `null`, mostly because the node environment does not handle regex the same way a browser does. By adding a `not null` check, we can circumvent this problem.
This PR also improves the code readability of this plugin a bit by using a separate function for getting the correct regex..
> fix: make sure the regex exec result is not null

- packages/dullahan-runner-aws-lambda/src/DullahanRunnerAwsLambda.ts
- packages/dullahan/src/api/DullahanApi.ts
Max sure max concurrency is set properly because of not it will pass/use infinity
> chore: log max concurrency

- packages/dullahan/src/api/DullahanApi.ts
Use the getText command to get the text before clearing.
> chore: use gettext inside of cleartext

- packages/dullahan-adapter-playwright/src/DullahanAdapterPlaywright.ts
- packages/dullahan-adapter-puppeteer/src/DullahanAdapterPuppeteer.ts
- packages/dullahan-adapter-selenium-3/src/DullahanAdapterSelenium3.ts
- packages/dullahan-adapter-selenium-4/src/DullahanAdapterSelenium4.ts
- packages/dullahan/src/adapter/DullahanAdapter.ts
- packages/dullahan/src/api/DullahanApi.ts
Implement a clearText function in the adapters that works for each adapter.
> chore: implement a clearText function that works

- packages/dullahan-runner-aws-lambda/src/DullahanRunnerAwsLambda.ts
Remove the loop since it's possible to get stuck in it.
> chore: remove do while function from lambda runner

- packages/dullahan-runner-aws-lambda/src/DullahanRunnerAwsLambda.ts
Reverts Kaartje2go/Dullahan#57
> chore: add do while function to lambda runner

- packages/dullahan-plugin-report-html/src/DullahanPluginReportHtml.ts
- packages/dullahan-plugin-report-json/src/DullahanPluginReportJson.ts
- packages/dullahan-plugin-report-markdown/src/DullahanPluginReportMarkdown.ts
The json, html and markdown report plugins now have better test deduping
logic that does not rely on the order of tests in the array. This should
make the plugins less likely to break in the future.
> chore: Better test deduping logic for report plugins

- packages/dullahan/src/api/DullahanApi.ts
When the file path is absolute, we should not change it.
> fix: do not change absolute file path

- packages/dullahan-adapter-selenium-4/src/DullahanAdapterSelenium4.ts
waitForElementNotPresent and waitForElementNotVisible now work correctly
in selenium 4
> fix: Fixes for waitForElementNot functions

- packages/dullahan-adapter-playwright/src/DullahanAdapterPlaywright.ts
- packages/dullahan-adapter-puppeteer/src/DullahanAdapterPuppeteer.ts
- packages/dullahan-adapter-selenium-3/src/DullahanAdapterSelenium3.ts
- packages/dullahan-adapter-selenium-4/src/DullahanAdapterSelenium4.ts
- packages/dullahan/src/DullahanCli.ts
- packages/dullahan/src/adapter/DullahanAdapter.ts
- packages/dullahan/src/api/DullahanApi.ts
This implements a function to fill a field in an iFrame. For now it will only work in Puppeteer / Playwright.
> feat: implement a function to fill a field in an iframe

- packages/dullahan-adapter-selenium-4/src/DullahanAdapterSelenium4.ts
This implments the `fillInIframeField` function for selenium 4.
> chore: implement the fill in iframe function for selenium 4

- packages/dullahan/src/nodejs_helpers/runModifiedTests.ts
> Change order of comparison

- packages/dullahan-runner-aws-lambda/src/DullahanRunnerAwsLambda.ts
> Add stop method to stop early

- packages/dullahan-runner-aws-lambda/src/DullahanRunnerAwsLambda.ts
> Revert async pool

- packages/dullahan-adapter-playwright/src/DullahanAdapterPlaywright.ts
- packages/dullahan-adapter-puppeteer/src/DullahanAdapterPuppeteer.ts
- packages/dullahan-adapter-selenium-3/src/DullahanAdapterSelenium3.ts
- packages/dullahan-adapter-selenium-4/src/DullahanAdapterSelenium4.ts
- packages/dullahan/src/adapter/DullahanAdapter.ts
- packages/dullahan/src/api/DullahanApi.ts
* Added the `clickIFrameElement` function to click a given element inside of a given iframe
> feat: Added clickIFrameElement

- packages/dullahan-runner-aws-lambda/src/DullahanRunnerAwsLambda.ts
Is it possible to have a race condition in that case?
> on idle can have race condition together with start

- packages/dullahan-runner-aws-lambda/package.json
- packages/dullahan-runner-aws-lambda/src/DullahanRunnerAwsLambda.ts
> p-queue not use await

- packages/dullahan-runner-aws-lambda/package.json
- packages/dullahan-runner-aws-lambda/src/DullahanRunnerAwsLambda.ts
> Lower concurrency per failure

- packages/dullahan-plugin-report-html/template/partials/test.ejs
> Add timestamp

- packages/dullahan-plugin-report-html/template/partials/test.ejs
Update template again to include proper timestamp instead of only number
> Update template to have proper formatted timestamp

- packages/dullahan-runner-standard/src/DullahanRunnerStandard.ts
- packages/dullahan/src/nodejs_helpers/runModifiedTests.ts
When file is present we run only changed files in test folder even though we modified file outside of that folder
> Run only modified by adding file

- packages/dullahan-adapter-selenium-3/src/DullahanAdapterSelenium3.ts
- packages/dullahan-plugin-github/src/DullahanPluginGithub.ts
- packages/dullahan/src/api/DullahanApiOptions.ts
- scripts/jest/config/env_nodejs.js
- scripts/jest/setup/before_all_browser.js
- scripts/jest/setup/before_test_nodejs.ts
Basically a revert of;
#147 
#146 
#145
> revert timeout changes

- packages/dullahan/src/browser_helpers/findElement.ts
Fixed a bug where waitForElementNotVisible and waitForElementNotPresent
always succeeded
> fix: fixed waitForElementNotVisible, waitForElementNotPresent

- packages/dullahan-adapter-puppeteer/src/DullahanAdapterPuppeteer.ts
- packages/dullahan/src/browser_helpers/findElement.ts
Earlier fixes for puppeteer for the waitForElementNotPresent and
waitForElementNotVisible fnctions broke these function in selenium, this
PR partialy reverts the changes and creates a proper fix, that works in
both selenium and puppeteer.
> fix: fixes waitForElementNotPresent, waitForElementNotVisible

- packages/dullahan-plugin-report-html/src/DullahanPluginReportHtml.ts
Time could be wrong because cached
> Set time from constructor to prevent incorrect cached time

- packages/dullahan-adapter-puppeteer/src/DullahanAdapterPuppeteer.ts
- packages/dullahan-runner-aws-lambda/src/DullahanRunnerAwsLambda.ts
- packages/dullahan/src/api/DullahanApi.ts
setURL can break when dialog is present
> setURL can break when dialog is present

- packages/dullahan-adapter-puppeteer/package.json
- packages/dullahan-adapter-puppeteer/src/DullahanAdapterPuppeteer.ts
- packages/dullahan/src/adapter/DullahanAdapter.ts
- yarn.lock
> Chrome aws 6

- packages/dullahan-runner-aws-lambda/src/DullahanRunnerAwsLambda.ts
Can run in timeout when having a lot of failures so better to stop early
> Stop when have 20 tests failing

- packages/dullahan-plugin-github/src/DullahanPluginGithub.ts
> Improve error logging for Github plugin

- __snapshots__/env_nodejs/exports.ts.snap
- packages/dullahan-plugin-github/src/DullahanPluginGithub.ts
- packages/dullahan-plugin-github/src/DullahanPluginGithubOptions.ts
- packages/dullahan-plugin-github/src/helpers/formatter.ts
- packages/dullahan-plugin-github/src/helpers/index.ts
To use this feature set the enableDetailedStatusChecks
option to true
> feat: add detailed status checks for github

- package.json
- yarn.lock
Reverts Kaartje2go/Dullahan#214
> Revert "chore(deps): update dependency typedoc to ^0.22.0"

- package.json
- yarn.lock
update the jest/types package since it is needed for the node upgrade
> deps: update jest types

- packages/dullahan-runner-aws-lambda/package.json
- packages/dullahan-runner-standard/package.json
- yarn.lock
Reverts Kaartje2go/Dullahan#242
> Revert "fix(deps): update dependency tiny-async-pool to v2"

- packages/dullahan-adapter-selenium-4/src/DullahanAdapterSelenium4.ts
https://www.browserstack.com/docs/automate/selenium/error-codes/keep-alive-not-used
> fix: add keep alive to https

- package.json
- yarn.lock
Upgrade the chromedriver dependency
> chore: upgrade chromedriver

- package.json
- packages/dullahan-plugin-aws-s3/package.json
- packages/dullahan-plugin-browserstack/src/DullahanPluginBrowserstack.ts
- packages/dullahan-runner-aws-lambda/package.json
- yarn.lock
The docs mention that a `reason` might be required, so by providing an empty string, hopefully it will indeed set the session status
> fix: attempt to set browserstack session status

- package.json
- packages/dullahan-adapter-selenium-3/package.json
- packages/dullahan-plugin-aws-s3/package.json
- packages/dullahan-plugin-report-html/package.json
- packages/dullahan-runner-aws-lambda/package.json
- packages/dullahan-runner-aws-lambda/src/DullahanRunnerAwsLambda.ts
- yarn.lock
Updates to mostly linting / dev related dependencies
> deps: update various dependencies

- packages/dullahan-adapter-puppeteer/package.json
- yarn.lock
Reverts Kaartje2go/Dullahan#304
> Revert "update puppeteer"
